[build]
  command = "python -m pip install -r requirements.txt && python -m uvicorn app:app --host 0.0.0.0 --port 8000"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200